[2023-05-13T12:56:22.149+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=schedule-training/run_id=manual__2023-05-13T12:56:20.456006+00:00/task_id=get_data permission to 509
[2023-05-13T12:56:22.188+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=schedule-training/run_id=manual__2023-05-13T12:56:20.456006+00:00/task_id=get_data permission to 509
[2023-05-13T12:56:22.482+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: schedule-training.get_data manual__2023-05-13T12:56:20.456006+00:00 [queued]>
[2023-05-13T12:56:22.491+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: schedule-training.get_data manual__2023-05-13T12:56:20.456006+00:00 [queued]>
[2023-05-13T12:56:22.492+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-05-13T12:56:22.510+0000] {taskinstance.py:1350} INFO - Executing <Task(_PythonDecoratedOperator): get_data> on 2023-05-13 12:56:20.456006+00:00
[2023-05-13T12:56:22.517+0000] {standard_task_runner.py:57} INFO - Started process 972 to run task
[2023-05-13T12:56:22.521+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'schedule-training', 'get_data', 'manual__2023-05-13T12:56:20.456006+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/scheduler.py', '--cfg-path', '/tmp/tmpj2_u4o_g']
[2023-05-13T12:56:22.524+0000] {standard_task_runner.py:85} INFO - Job 11: Subtask get_data
[2023-05-13T12:56:22.599+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=schedule-training/run_id=manual__2023-05-13T12:56:20.456006+00:00/task_id=get_data permission to 509
[2023-05-13T12:56:22.604+0000] {task_command.py:410} INFO - Running <TaskInstance: schedule-training.get_data manual__2023-05-13T12:56:20.456006+00:00 [running]> on host 7782a178ca1f
[2023-05-13T12:56:22.705+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='schedule-training' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2023-05-13T12:56:20.456006+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-13T12:56:20.456006+00:00'
[2023-05-13T12:56:22.712+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 220, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scheduler.py", line 23, in get_data
    with open(json_path, "r") as file:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/c/Users/Jonas/Programming/airflow/models.json'
[2023-05-13T12:56:22.731+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=schedule-training, task_id=get_data, execution_date=20230513T125620, start_date=20230513T125622, end_date=20230513T125622
[2023-05-13T12:56:22.750+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 11 for task get_data ([Errno 2] No such file or directory: '/mnt/c/Users/Jonas/Programming/airflow/models.json'; 972)
[2023-05-13T12:56:22.773+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-13T12:56:22.793+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
